/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 cultureConnection2.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("models/cultureConnection2.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.006, 0, -0.812]}
        rotation={[0, -0.889, 0]}
        scale={2.503}
      >
        <mesh geometry={nodes.Sphere004.geometry} material={materials.water} />
        <mesh
          geometry={nodes.Sphere004_1.geometry}
          material={materials.earth}
        />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.Hand}
        position={[-2.296, 0.207, 1.273]}
        rotation={[Math.PI / 2, 0, 0.315]}
        scale={[0.284, 1.237, 1.048]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.Hand}
        position={[-0.738, 0.8, 1.964]}
        rotation={[-2.967, 0.426, 3.127]}
        scale={[0.476, 0.605, 0.476]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.Hand}
        position={[2.244, 0.207, 1.062]}
        rotation={[-Math.PI / 2, 0, 0.523]}
        scale={[-0.284, -1.237, -1.048]}
      />
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials.Hand}
        position={[0.74, 0.8, 1.863]}
        rotation={[0.554, 0.283, -0.11]}
        scale={[0.476, 0.605, 0.476]}
      />
    </group>
  );
}

useGLTF.preload("/cultureConnection2.glb");
